spring:
  application:
    name: Campung
  config:
    import: optional:classpath:properties/env.properties
    
  # MariaDB 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3312}/${DB_NAME:campung}
    username: ${DB_USERNAME:campung}
    password: ${DB_PASSWORD:campung1234}
  
  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Redis 설정  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:campung1234}

# 서버 포트 설정
server:
  port: ${SERVER_PORT:8080}

# Firebase 설정
firebase:
  config:
    path: firebase-service-account.json

# Swagger/OpenAPI 설정 (간소화)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
